// Code generated by 'yaegi extract github.com/sircodemane/yaegi-plugin/pkg/sdk'. DO NOT EDIT.

package lib

import (
	"github.com/sircodemane/yaegi-plugin/pkg/sdk"
	"net/http"
	"reflect"
)

func init() {
	Symbols["github.com/sircodemane/yaegi-plugin/pkg/sdk/sdk"] = map[string]reflect.Value{
		// type definitions
		"Plugin":            reflect.ValueOf((*sdk.Plugin)(nil)),
		"PluginConstructor": reflect.ValueOf((*sdk.PluginConstructor)(nil)),

		// interface wrapper definitions
		"_Plugin": reflect.ValueOf((*_github_com_sircodemane_yaegi_plugin_pkg_sdk_Plugin)(nil)),
	}
}

// _github_com_sircodemane_yaegi_plugin_pkg_sdk_Plugin is an interface wrapper for Plugin type
type _github_com_sircodemane_yaegi_plugin_pkg_sdk_Plugin struct {
	IValue  interface{}
	WRoutes func() map[string]http.HandlerFunc
}

func (W _github_com_sircodemane_yaegi_plugin_pkg_sdk_Plugin) Routes() map[string]http.HandlerFunc {
	return W.WRoutes()
}
