// Code generated by 'yaegi extract github.com/sircodemane/yaegi-plugin/pkg/sdk/myapp'. DO NOT EDIT.

package lib

import (
	"github.com/sircodemane/yaegi-plugin/pkg/sdk/myapp"
	"reflect"
)

func init() {
	Symbols["github.com/sircodemane/yaegi-plugin/pkg/sdk/myapp/myapp"] = map[string]reflect.Value{
		// type definitions
		"MyAppInterface": reflect.ValueOf((*myapp.MyAppInterface)(nil)),
	}
}
